export type LoansQueryDto = {
  select?: string;
  skip?: string;
  take?: string;
  order?: string;
  filter?: string;
  join?: string;
  investable?: boolean;
};

export type LoanResponseData = {
  id: string;
  no: number;
  applicationId: string;
  userId: number;
  name: string;
  category: string;
  state: string;
  isDisplayed: boolean;
  paymentDate: string;
  dueDate: string;
  repaymentDate: string;
  period: number;
  interestRate: number;
  overdueInterestRate: number;
  investorFeeRate: number;
  borrowerFeeRate: number;
  fundAmount: number;
  investedAmount: number;
  expectedAmount: number;
  repaymentAmount: number;
  principal: number;
  interestAmount: number;
  investorFeeAmount: number;
  borrowerFeeAmount: number;
  taxAmount: number;
  repaymentType: string;
  repaymentCycle: number;
  repaymentCount: number;
  wcTid: string;
  wcRtid: string;
  wcKeepid: string;
  kftcLoanRegisterId: string;
  kftcLoanContractId: string;
  kftcGoodsId: string;
  memo: string;
  data: Record<string, unknown>;
  createdAt: Date;
  updatedAt: Date;
  userInvestedAmount: number;
  isUserInvested: boolean;
  investmentId: number | null;
  reservedAt: Date;
  investableOnBorrower?: number;
  investableLimit?: number;
  code?: string;
};

export type LoansResponse = Array<LoanResponseData>;
